from __future__ import annotations

import logging
import os
from pathlib import Path


_COLORS = {
    "DEBUG": "\033[36m",
    "INFO": "\033[32m",
    "WARNING": "\033[33m",
    "ERROR": "\033[31m",
    "CRITICAL": "\033[35m",
    "RESET": "\033[0m",
}

_FORMAT = "%(asctime)s | %(levelname)-8s | %(message)s"
_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"


class _ColorFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        color = _COLORS.get(record.levelname, "")
        reset = _COLORS["RESET"]
        record.levelname = f"{color}{record.levelname:<8}{reset}"
        record.msg = f"{color}{record.msg}{reset}"
        return super().format(record)


class _StepAdapter(logging.LoggerAdapter):
    def process(self, msg: str, kwargs: dict) -> tuple[str, dict]:
        step = self.extra.get("step", "") if self.extra else ""
        if step:
            return f"[{step}] {msg}", kwargs
        return msg, kwargs


def setup_logging(log_dir: str, run_id: str) -> logging.Logger:
    logger = logging.getLogger("sprint-runner")
    logger.setLevel(logging.DEBUG)

    logger.handlers.clear()

    # Console handler: INFO, colored
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(_ColorFormatter(_FORMAT, _DATE_FORMAT))
    logger.addHandler(console)

    # File handler: DEBUG, plain text
    Path(log_dir).mkdir(parents=True, exist_ok=True)
    log_file = os.path.join(log_dir, f"sprint-run-{run_id}.log")
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter(_FORMAT, _DATE_FORMAT))
    logger.addHandler(file_handler)

    # Summary file: only lifecycle events
    summary_path = os.path.join(log_dir, "sprint-summary.log")
    summary_handler = logging.FileHandler(summary_path, encoding="utf-8")
    summary_handler.setLevel(logging.INFO)
    summary_handler.setFormatter(logging.Formatter("%(asctime)s | %(message)s", _DATE_FORMAT))
    summary_handler.addFilter(lambda r: getattr(r, "_summary", False) is True)
    logger.addHandler(summary_handler)

    # Ensure sprint-logs/ is gitignored so logs never get committed
    _ensure_gitignore(log_dir)

    return logger


def _ensure_gitignore(log_dir: str) -> None:
    """Create or update .gitignore in the log directory."""
    gitignore_path = os.path.join(log_dir, ".gitignore")
    if os.path.exists(gitignore_path):
        return
    with open(gitignore_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by sprint-runner.py\n")
        f.write("*\n")


def get_step_logger(logger: logging.Logger, step: str) -> _StepAdapter:
    return _StepAdapter(logger, {"step": step})


def log_summary(logger: logging.Logger, msg: str) -> None:
    record = logger.makeRecord(
        logger.name, logging.INFO, "", 0, msg, (), None
    )
    record._summary = True  # type: ignore[attr-defined]
    logger.handle(record)
